name: sartex
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+12

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  uuid: ^4.4.2
  flutter_svg: ^2.0.2
  shared_preferences: ^2.0.18
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  syncfusion_flutter_datagrid: ^26.2.8
  table_calendar: ^3.0.9
  syncfusion_flutter_datagrid_export: ^26.2.8
  excel: ^4.0.3
  text_scroll: ^0.2.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  fonts:
    - family: Agency FB
      fonts:
        - asset: assets/fonts/agencyfb_reg.ttf
    - family: NotoSansArmenian
      fonts:
        - asset: assets/fonts/NotoSansArmenianRegular.ttf
    - family: Sylfaen
      fonts:
        - asset: assets/fonts/Sylfaen.ttf

  uses-material-design: true
  assets:
    - assets/

